// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAacSv4SPa-RwtnSsHqoPEYlnLoa93q_ss',
    appId: '1:619446246965:web:b5b03d21f8e94d84f99b7c',
    messagingSenderId: '619446246965',
    projectId: 'test-project-ef6c7',
    authDomain: 'test-project-ef6c7.firebaseapp.com',
    storageBucket: 'test-project-ef6c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaAL8aZCAjv48GDlEubP6dipfba3tNrOM',
    appId: '1:619446246965:android:07069036bb2f9386f99b7c',
    messagingSenderId: '619446246965',
    projectId: 'test-project-ef6c7',
    storageBucket: 'test-project-ef6c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtfuV61EhiUTyZo1jgFc6rDh96RGiHyc',
    appId: '1:619446246965:ios:32aa5ce29927a709f99b7c',
    messagingSenderId: '619446246965',
    projectId: 'test-project-ef6c7',
    storageBucket: 'test-project-ef6c7.firebasestorage.app',
    iosBundleId: 'com.example.myzikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtfuV61EhiUTyZo1jgFc6rDh96RGiHyc',
    appId: '1:619446246965:ios:32aa5ce29927a709f99b7c',
    messagingSenderId: '619446246965',
    projectId: 'test-project-ef6c7',
    storageBucket: 'test-project-ef6c7.firebasestorage.app',
    iosBundleId: 'com.example.myzikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAacSv4SPa-RwtnSsHqoPEYlnLoa93q_ss',
    appId: '1:619446246965:web:2aa15c3d3ff53c25f99b7c',
    messagingSenderId: '619446246965',
    projectId: 'test-project-ef6c7',
    authDomain: 'test-project-ef6c7.firebaseapp.com',
    storageBucket: 'test-project-ef6c7.firebasestorage.app',
  );
}
